# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Sarwar Bhuiyan's Blog
tagline:          ''
description:      ''
url:              https://sarwarbhuiyan.github.io
baseurl:          /sarwar

author:
  name:           'Sarwar Bhuiyan'
  url:            https://twitter.com/sarwarbhuiyan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sarwarbhuiyan/sarwarbhuiyan.github.io
